test(deps): update dependency com.google.truth:truth to v1.4.0 (#3115)
[![Mend Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [com.google.truth:truth](https://togithub.com/google/truth) | `1.3.0` -> `1.4.0` | [![age](https://developer.mend.io/api/mc/badges/age/maven/com.google.truth:truth/1.4.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![adoption](https://developer.mend.io/api/mc/badges/adoption/maven/com.google.truth:truth/1.4.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![passing](https://developer.mend.io/api/mc/badges/compatibility/maven/com.google.truth:truth/1.3.0/1.4.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) | [![confidence](https://developer.mend.io/api/mc/badges/confidence/maven/com.google.truth:truth/1.3.0/1.4.0?slim=true)](https://docs.renovatebot.com/merge-confidence/) |

---

### Release Notes

<details>
<summary>google/truth (com.google.truth:truth)</summary>

### [`v1.4.0`](https://togithub.com/google/truth/releases/tag/v1.4.0): 1.4.0

In this release, our assertions on Java 8 types continue to move from the `Truth8` class to the main `Truth` class. This change should not break compatibility for any supported JDK or Android version, even users who test under old versions of Android without [API desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring). Additionally, we will never break binary compatibility, though some users will have to make changes to their source code in order for it to compile against newer versions.

This release is likely to lead to more **build failures** than [1.3.0](https://togithub.com/google/truth/releases/tag/v1.3.0) did. However, those failures should be **straightforward to fix**.

#### Example build failure

    Foo.java:152: error: reference to assertThat is ambiguous
        assertThat(repo.findFileWithName("foo")).isNull();
        ^
      both method assertThat(@&#8203;org.jspecify.nullness.Nullable Path) in Truth8 and method assertThat(@&#8203;org.jspecify.nullness.Nullable Path) in Truth match

#### Simplest upgrade strategy (if you can update all your code atomically in the same commit as the Truth upgrade)

In the same commit:

1.  Upgrade Truth to 1.4.0.
2.  Replace `import static com.google.common.truth.Truth8.assertThat;` with `import static com.google.common.truth.Truth.assertThat;`.
    -   If you use Kotlin, replace `import com.google.common.truth.Truth8.assertThat` with `import com.google.common.truth.Truth.assertThat`.
3.  Replace `import com.google.common.truth.Truth8;` with `import com.google.common.truth.Truth;`.
    -   again, similarly for Kotlin if needed
4.  Replace remaining references to `Truth8` with references to `Truth`.
    -   For example, replace `Truth8.assertThat(optional).isPresent()` with `Truth.assertThat(optional).isPresent()`.

If you're feeling lucky, you can try this one-liner for the code updates:

```sh
git grep -l Truth8 | xargs perl -pi -e 's/import static com.google.common.truth.Truth8.assertThat;/import static com.google.common.truth.Truth.assertThat;/g; s/import com.google.common.truth.Truth8.assertThat/import com.google.common.truth.Truth.assertThat/g; s/import com.google.common.truth.Truth8/import com.google.common.truth.Truth/g; s/\bTruth8[.]/Truth./g;'
```

After that process, it is possible that you'll still see build errors from ambiguous usages of `assertThat` static imports. If so, you can find a workaround in the section about overload ambiguity in the release notes for [1.3.0](https://togithub.com/google/truth/releases/tag/v1.3.0). Alternatively, you can wait to upgrade until after a future Truth release, which will eliminate the ambiguity by changing the signatures of some `Truth.assertThat` overloads.

#### Incremental upgrade strategy

If you have a very large repo or you have other reasons to prefer to upgrade incrementally, you can use the approach that we used inside Google. Roughly, that approach was:

1.  Make the optional changes discussed in the release notes for [1.3.0](https://togithub.com/google/truth/releases/tag/v1.3.0).
2.  For any remaining calls to `Truth8.assertThat`, change them to *avoid* static import.
    -   That is, replace `assertThat(optional).isPresent()` with `Truth8.assertThat(optional).isPresent()`.
3.  Upgrade Truth to 1.4.0.
4.  Optionally replace references to `Truth8` with references to `Truth` (including restoring static imports if desired), as discussed in section about the simple upgrade strategy above.

#### Optional additional changes

-   If you use `assertWithMessage(...).about(intStreams()).that(...)`, `expect.about(optionalLongs()).that(...)`, or similar, you can remove your call to `about`. This change will never be necessary; it is just a simplification.
    -   This is similar to a previous optional change from [1.3.0](https://togithub.com/google/truth/releases/tag/v1.3.0), except that 1.3.0 solved this problem for `streams` and `optionals`, whereas 1.4.0 solves it for the other `Truth8` types.

#### For help

Please feel welcome to [open an issue](https://togithub.com/google/truth/issues/new) to report problems or request help.

#### Changelog

-   Added the remaining `Truth8.assertThat` overloads to the main `Truth` class. ([`9be8e77`](https://togithub.com/google/truth/commit/9be8e774c), [`1f81827`](https://togithub.com/google/truth/commit/1f81827f1))
-   Added more `that` overloads to make it possible to write type-specific assertions when using the remaining Java 8 types. ([`7c65fc6`](https://togithub.com/google/truth/commit/7c65fc611))

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Mend Renovate](https://www.mend.io/free-developer-tools/renovate/). View repository job log [here](https://developer.mend.io/github/googleapis/java-bigquery).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xNTMuMiIsInVwZGF0ZWRJblZlciI6IjM3LjE3MC4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->