ci: owlbot update lock job not to use gcloud (#9238)
Previous attemt #9236 failed: https://togithub.com/googleapis/google-cloud-java/actions/runs/4439720566/jobs/7792573842

```
WARNING: Could not open the configuration file: [/home/runner/.config/gcloud/configurations/config_default].
ERROR: (gcloud.container.images.describe) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
```

To use gcloud command, it requires authentication even when the image is publicly available.

Therefore, changing it to use curl command.