fix: normalize indentation in owlbot yamls for new libraries (#12759)
Fixes the following failure occured in
https://github.com/googleapis/google-cloud-java/pull/12756
([job](https://github.com/googleapis/google-cloud-java/actions/runs/24256669481/job/70829822721?pr=12756)):

```
YAMLException: end of the stream or a document separator is expected (24:1)

 21 | 
 22 | deep-preserve-regex:
 23 |  - "/google-.*/src/test/java/co ...
 24 | - "/.*google-.*/src/main/java/c ...
------^
 25 | 
 26 | deep-copy-regex:
```
 
The approach is to keep the indentation as 0 spaces before the dash.
Added unit tests to confirm this.
Also modified the yaml template to handle special cases such as
`io/grafeas` instead of `com/google/cloud/service/...`